blank_issues_enabled: false
contact_links:
    - name: 🤔 Questions and Help
      url: https://github.com/bketelsen/IncusScripts/discussions
      about: For suggestions or questions, please use the Discussions section.
